### ISSUE TITLE
Handling incomplete addresses

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/jquery-findyourrep#1]
If you enter a very incomplete address, such as just a number, it just shows a blank listing:
![screen shot 2014-03-07 at 10 48 22 am](https://f.cloud.github.com/assets/3171982/2358743/0bf242c4-a610-11e3-8d7b-5a14a4cf0866.png)

Might be helpful to include an error message and instruct users to enter a full address. Another curious issue with this is that if you enter a street number and a street name it returns different states. For example, here is "1900 N street":
![screen shot 2014-03-07 at 10 50 46 am](https://f.cloud.github.com/assets/3171982/2358774/5d0be318-a610-11e3-8da8-fcc2e166acfd.png)

Here is "1 2nd street":
![screen shot 2014-03-07 at 10 51 55 am](https://f.cloud.github.com/assets/3171982/2358782/730edf6c-a610-11e3-8b7c-1b2c04343c27.png)

"99 Walsh Road":
![screen shot 2014-03-07 at 10 52 44 am](https://f.cloud.github.com/assets/3171982/2358792/8dc9d938-a610-11e3-9327-3575a0b0b2fc.png)

**Comment by drinks** [comment]
Yeah the first case Is a definite yes from me. As for the 2nd, I'm not real interested in doing address validation. The example uses Google's geocoder and just takes the top result it returns. I think 'follows the placeholder example with some degree of success' is the baseline user I'm willing to support here.
