### ISSUE TITLE
Note the HTTPS limitations

### ISSUE THREAD

**Issue by konklone** [sunlightlabs/jquery-findyourrep#3]
When the docs themselves are [loaded over HTTPS](https://sunlightlabs.github.io/jquery-findyourrep/), the lookup silently breaks on state legislators, and only returns federal legislators. This is because the Open States API is not available over `https://`.

The docs should mention this limitation somewhere. Additionally, the library should probably proactively decline to make the OS API request when the page it's on is over HTTP, and at least log to the console why not.

**Comment by drinks** [comment]
Both good points, on it.

**Comment by konklone** [comment]
For anyone's reference, there's a [related ticket](https://sunlight.atlassian.net/browse/OS-26) on the Open States issue tracker.

**Comment by drinks** [comment]
Fixed in df952a4.
